# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
- requiredAuthorRole: OWNER
  minApprovals:
    OWNER: 0
- minApprovals:
    OWNER: 0
- minApprovals:
    OWNER: 0
- requiredLabels:
  - merge

mergeCommitMessage: "{title} (#{number})"
